spring:
  application:
    name: vente-chaussure
  datasource:
    username: ventechaussure
    password: ventechaussure
    url: jdbc:mysql://localhost:3306/ventechaussure
  jpa:
    hibernate:
      #ddl-auto permet de supprimer et de creer les tables
      ddl-auto: create
    show-sql: true